# Generated by Django 5.0.6 on 2024-07-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorpatientassociation',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='doctorpatientassociation',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.AlterUniqueTogether(
            name='doctorpatientassociation',
            unique_together={('doctor_id', 'patient_id')},
        ),
    ]
