# Generated by Django 5.0.6 on 2024-08-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('prescription_id', models.IntegerField()),
                ('operation', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('medication_id', models.IntegerField()),
                ('description', models.TextField()),
                ('dose', models.CharField(max_length=255)),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
            ],
        ),
    ]
