# Generated by Django 5.0.6 on 2024-08-23 00:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprescription',
            name='medication_id',
        ),
        migrations.AddField(
            model_name='medicalprescription',
            name='medication_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
