# Generated by Django 5.0.6 on 2024-09-02 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescriptions', '0002_remove_medicalprescription_medication_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 3, 25, 1, 526122, tzinfo=datetime.timezone.utc)),
        ),
    ]
