# Generated by Django 5.0.6 on 2024-09-07 01:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescriptions', '0002_remove_medicalprescription_medication_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalprescription',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
