# Generated by Django 5.0.6 on 2024-09-07 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescriptions', '0003_medicalprescription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 22, 40, 25, 279149, tzinfo=datetime.timezone.utc)),
        ),
    ]
