# Generated by Django 5.0.6 on 2024-09-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescriptions', '0004_alter_medicalprescription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
