# Generated by Django 5.0.6 on 2024-09-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_prescriptions', '0005_alter_medicalprescription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprescription',
            name='dose',
        ),
    ]
